name: Android APK Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses and install components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x android-app/gradlew

      - name: Build debug APK
        working-directory: android-app
        run: ./gradlew :app:assembleDebug --no-daemon

      - name: Copy APK into finishs folder
        run: |
          mkdir -p finishs
          cp android-app/app/build/outputs/apk/debug/*.apk finishs/

      - name: Commit APK to repository (finishs/)
        uses: EndBug/add-and-commit@v9
        with:
          add: 'finishs/*.apk'
          message: 'chore: add debug APK to finishs [skip ci]'
          default_author: github_actions
          branch: ${{ github.event.repository.default_branch }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android-app/app/build/outputs/apk/debug/*.apk

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: android-app/app/build/outputs/apk/debug/*.apk

      - name: Create Draft Release (manual run)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: manual-${{ github.run_id }}
          name: Manual build ${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          files: android-app/app/build/outputs/apk/debug/*.apk

